# CLI tools
brew "git"
brew "fzf"
brew "wget"
brew "tree"
brew "gnupg"
brew "neovim",
brew "ripgrep"
brew "pinentry-mac"
brew "go"
brew "node"
brew "lua-language-server"
brew "stylua"
brew "biome"
brew "shfmt"

# Apps
cask "syncthing-app"
cask "domzilla-caffeine"
cask "loop"
cask "transmission"
cask "pearcleaner"
cask "itsycal"
cask "vlc"
cask "pika"
cask "keepassxc"
cask "telegram"
cask "brave-browser@nightly"
cask "ghostty"
cask "firefox"
cask "obsidian"
cask "figma"
cask "affinity"

# Fonts
cask "font-source-sans-3"
cask "font-iosevka"
cask "font-hermit"

# Go packages
go "golang.org/x/tools/gopls"

# Mac App Store apps
mas "WireGuard", id: 1451685025
