# Tools
brew "git"
brew "fzf"
brew "tree"
brew "wget"
brew "neovim"
brew "ripgrep"
brew "gnupg"
brew "pinentry-mac"
brew "diff-so-fancy"

# Runtimes
brew "node"

# LSPs
brew "lua-language-server"

# Formatters
brew "stylua"
brew "beautysh"
brew "shfmt"
brew "biome"

# Apps
cask "syncthing-app"
cask "domzilla-caffeine"
cask "loop"
cask "transmission"
cask "pearcleaner"
cask "vlc"
cask "the-unarchiver"
cask "itsycal"
cask "pika"
cask "keepassxc"
cask "telegram"
cask "helium-browser"
cask "ghostty"
cask "obsidian"
cask "figma"
cask "affinity"

# Fonts
cask "font-source-sans-3"
cask "font-ibm-plex-mono"
cask "font-cascadia-mono"
cask "font-iosevka"
cask "font-hermit"

# Go packages
go "golang.org/x/tools/gopls"

# Mac App Store apps
mas "WireGuard", id: 1451685025
