# Tools
brew "git"
brew "fzf"
brew "tree"
brew "wget"
brew "neovim"
brew "ripgrep"
brew "gnupg"
brew "pinentry-mac"
brew "diff-so-fancy"

# Runtimes
brew "node"

# LSPs
brew "lua-language-server"

# Formatters
brew "stylua"
brew "beautysh"
brew "shfmt"
brew "biome"

# Apps
cask "syncthing-app"
cask "loop"
cask "transmission"
cask "pearcleaner"
cask "iina"
cask "keepassxc"
cask "telegram"
cask "firefox"
cask "ghostty"
cask "figma"
cask "affinity"
cask "jimeh/emacs-builds/emacs-app"

# Fonts
cask "font-sf-mono"
cask "font-source-sans-3"
cask "font-source-code-pro"

# Mac App Store apps
mas "WireGuard", id: 1451685025
