# CLI Tools
brew "git"
brew "fzf"
brew "wget"
brew "tree"
brew "mise"
brew "gnupg"
brew "ripgrep"
brew "neovim"
brew "pinentry-mac"

# Applications
cask "rectangle"
cask "syncthing"
cask "pika"
cask "domzilla-caffeine"
cask "pearcleaner"
cask "vlc"
cask "the-unarchiver"
cask "keepassxc"
cask "telegram"
cask "visual-studio-code"
cask "brave-browser"
cask "firefox"
cask "figma"
cask "obsidian"
cask "kitty"
cask "transmission"
cask "hammerspoon"

# Fonts
cask "font-source-sans-3"

# VS Code Extensions
vscode "pkief.material-icon-theme"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
