# CLI Tools
brew "git"
brew "fzf"
brew "wget"
brew "tree"
brew "gnupg"
brew "ripgrep"
brew "neovim"
brew "pinentry-mac"

# Development Tools
brew "node"
brew "go"
brew "stylua"
brew "lua-language-server"

# Applications
cask "syncthing-app"
cask "pika"
cask "transmission"
cask "pearcleaner"
cask "domzilla-caffeine"
cask "the-unarchiver"
cask "vlc"
cask "keepassxc"
cask "telegram"
cask "visual-studio-code"
cask "firefox"
cask "obsidian"
cask "alacritty"

# Fonts
cask "font-source-sans-3"

# VS Code Extensions
vscode "pkief.material-icon-theme"
vscode "usernamehw.errorlens"
vscode "vscodevim.vim"
